// Generated by CoffeeScript 1.7.1
(function() {
  var GroundStop, request;

  request = require('request');

  GroundStop = (function() {
    var BASE_URL;

    function GroundStop() {}

    BASE_URL = "http://services.faa.gov/airport/status";

    GroundStop.prototype.buildUrl = function(options) {
      return "" + BASE_URL + "/" + options.airport;
    };

    GroundStop.prototype.fetch = function(options, cb) {
      var airport, requestOptions;
      airport = options.airport;
      requestOptions = {
        url: this.buildUrl({
          airport: airport
        }),
        json: true
      };
      return request(requestOptions, function(err, res, body) {
        return cb(err, body);
      });
    };

    return GroundStop;

  })();

  module.exports = GroundStop;

}).call(this);
